/**
 * Self-hosts the two Google Fonts so the site makes no external requests at all.
 *
 *   node tools/fetch-fonts.mjs
 *
 * Downloads the woff2 files for Fraunces and Inter into
 * cms/wwwroot/fonts/, writes a local @font-face stylesheet, and rewrites the
 * <link> tags in the layout and the static page to use it.
 *
 * After this the site renders identically with no internet connection.
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const FONT_DIR = "cms/wwwroot/fonts";
mkdirSync(FONT_DIR, { recursive: true });

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900" +
  "&family=Inter:wght@300;400;500;600;700&display=swap";

const css = await (
  await fetch(CSS_URL, { headers: { "User-Agent": UA } })
).text();

/* --------------------------------------------------------------- download */

const blocks = css.split("@font-face").filter((b) => b.includes("url("));
const faces = [];
let subset = 0;

for (const block of blocks) {
  const url = block.match(/url\((https:\/\/[^)]+)\)/)?.[1];
  if (!url) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] || "font";
  const weight = block.match(/font-weight:\s*([\d\s]+)/)?.[1].trim() || "400";
  const style = block.match(/font-style:\s*(\w+)/)?.[1] || "normal";
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];

  // stable filename. The unicode-range subset must be part of it, otherwise
  // every subset of a weight collides on one filename and the later ones
  // overwrite the earlier, leaving most @font-face rules pointing at nothing.
  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const part = (i) => `p${String(i).padStart(2, "0")}`;
  const name = `${slug}-${weight.replace(/\s+/g, "_")}-${style}-${part(++subset)}.woff2`;

  const dest = join(FONT_DIR, name);
  if (!existsSync(dest) || statSync(dest).size < 1000) {
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    if (buf.length < 1000) {
      console.log(`  FAIL ${name} (${buf.length} bytes)`);
      continue;
    }
    writeFileSync(dest, buf);
    console.log(`  ok   ${String(Math.round(buf.length / 1024)).padStart(5)} KB  ${name}`);
  }

  faces.push(
    [
      "@font-face {",
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url('__FONT_PREFIX__${name}') format('woff2');`,
      range ? `  unicode-range: ${range};` : null,
      "}",
    ]
      .filter(Boolean)
      .join("\n")
  );
}

// The two builds live at different URL depths: Umbraco serves from /, the
// static page sits at /index.html, so a root-relative /fonts/ URL resolves
// against the stylesheet's own folder (assets/css/) in the static build.
// Emit a stylesheet per build with the prefix that is correct for each.
const mkCss = (prefix) =>
  "/* Self-hosted Fraunces + Inter, generated by tools/fetch-fonts.mjs.\n" +
  "   Replaces the Google Fonts <link> so the site makes no external requests. */\n\n" +
  faces.join("\n\n").replaceAll("__FONT_PREFIX__", prefix) +
  "\n";

writeFileSync("cms/wwwroot/css/fonts.css", mkCss("/fonts/"), "utf8");
mkdirSync("assets/css", { recursive: true });
writeFileSync("assets/css/fonts.css", mkCss("../fonts/"), "utf8");
console.log(`\nwrote cms/wwwroot/css/fonts.css (prefix /fonts/)`);
console.log(`wrote assets/css/fonts.css      (prefix ../fonts/)`);
console.log(`  ${faces.length} faces`);

/* ---------------------------------------------------------------- rewrite */

const LINK_RE =
  /\s*<link[^>]*href="https:\/\/fonts\.googleapis\.com\/css2[^"]*"[^>]*>/g;

for (const [file, rel] of [
  ["cms/Views/_Layout.cshtml", "/css/fonts.css"],
  ["index.html", "assets/css/fonts.css"],
]) {
  if (!existsSync(file)) continue;
  const before = readFileSync(file, "utf8");
  const after = before.replace(
    LINK_RE,
    `\n    <link rel="stylesheet" href="${rel}" />`
  );
  if (after !== before) {
    writeFileSync(file, after, "utf8");
    console.log(`  updated ${file}`);
  }
}

// drop the now-unneeded preconnects
for (const file of ["cms/Views/_Layout.cshtml", "index.html"]) {
  const before = readFileSync(file, "utf8");
  const after = before
    .replace(/\s*<link rel="preconnect" href="https:\/\/fonts\.(googleapis|gstatic)\.com[^>]*>/g, "")
    .replace(/\s*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com"[^>]*crossorigin[^>]*>/g, "");
  if (after !== before) {
    writeFileSync(file, after, "utf8");
    console.log(`  removed font preconnects in ${file}`);
  }
}